---
apiVersion: v1
kind: Namespace
metadata:
  name: shoot--foo--bar
---
apiVersion: v1
kind: Secret
metadata:
  name: default-token-5dtjz
  namespace: shoot--foo--bar
type: Opaque
data:
  token: dG9rZW4=
